version: "3.6"
services:
  elastic:
    container_name: elastic
    image: bakingbad/bcdhub-elastic:${TAG:-latest}
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data    
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    logging: &my-logging
      options:
        max-size: 10m
        max-file: "5"

  mq:
    container_name: mq
    image: rabbitmq:latest
    restart: always
    volumes:
      - mqdata:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    logging: *my-logging        

  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bcd
    volumes:
      - db:/var/lib/postgresql/data
    logging: *my-logging

  api:
    container_name: api
    restart: always
    image: bakingbad/bcdhub-api:${TAG:-latest}
    command: -f config.yml -f config.box.yml
    environment: 
      - GIN_MODE=release
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bcd
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    depends_on:
      - elastic
      - db
      - mq
    ports:
      - 127.0.0.1:42000:14000
    extra_hosts:
      sandbox: 172.17.0.1
    logging: *my-logging                                                                                      

  indexer:
    container_name: indexer
    restart: always
    image: bakingbad/bcdhub-indexer:${TAG:-latest}
    command: -f config.yml -f config.box.yml
    environment: 
      - GIN_MODE=release
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bcd
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    depends_on:
      - elastic
      - mq
    extra_hosts:
      sandbox: 172.17.0.1
    logging: *my-logging

  metrics:
    container_name: metrics
    restart: always
    image: bakingbad/bcdhub-metrics:${TAG:-latest}
    command: -f config.yml -f config.box.yml
    environment: 
      - GIN_MODE=release
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bcd
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    depends_on:
      - elastic
      - mq
      - db
    extra_hosts:
      sandbox: 172.17.0.1
    logging: *my-logging

  gui:
    container_name: gui
    restart: always
    image: bakingbad/bcdhub-gui:${TAG:-latest}
    entrypoint: /bin/bash
    command: -c "mv config.box.json config.json && nginx -g 'daemon off;'"
    depends_on:
      - api
    ports:
      - 127.0.0.1:8000:80
    logging: *my-logging

volumes:
  esdata:
  mqdata:
  db:
    driver: local
