rpc:
    mainnet:
        uri: https://mainnet-tezos.giganode.io
        timeout: 20
    zeronet:
        uri: https://rpc.tzkt.io/zeronet
        timeout: 20
    babylonnet:
        uri: https://rpc.tzkt.io/babylonnet
        timeout: 20
    carthagenet:
        uri: https://testnet-tezos.giganode.io
        timeout: 20

tzkt:
    mainnet:
        uri: https://api.tzkt.io/v1/
        services_uri: https://services.tzkt.io/v1/
        timeout: 20
    zeronet:
        uri: https://api.zeronet.tzkt.io/v1/
        services_uri: https://services.tzkt.io/zeronet/v1/
        timeout: 20
    babylonnet:
        uri: https://api.babylon.tzkt.io/v1/
        services_uri: https://services.tzkt.io/babylonnet/v1/
        timeout: 20
    carthagenet:
        uri: https://api.carthage.tzkt.io/v1/
        services_uri: https://services.tzkt.io/carthagenet/v1/
        timeout: 20

share:
    path: /etc/bcd

sentry:
    environment: staging
    uri: ${SENTRY_DSN}
    debug: false

oauth:
    state: ${OAUTH_STATE_STRING}
    jwt:
        secret: ${JWT_SECRET_KEY}
        redirect_url: https://you.better-call.dev/welcome
    github:
        client_id: ${GITHUB_CLIENT_ID}
        secret: ${GITHUB_CLIENT_SECRET}
        callback_url: https://you.better-call.dev/v1/oauth/github/callback
    gitlab:
        client_id: ${GITLAB_CLIENT_ID}
        secret: ${GITLAB_CLIENT_SECRET}
        callback_url: https://you.better-call.dev/v1/oauth/gitlab/callback

elastic:
    uri: http://elastic:9200
    timeout: 10

rabbitmq:
    uri: "amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@mq:5672/"
    queues:
        - operations
        - contracts
        - migrations
        - recalc

db:
    conn_string: "host=db port=5432 user=${POSTGRES_USER} dbname=bcd password=${POSTGRES_PASSWORD} sslmode=disable"

api:
    bind: ":42000"
    swagger_host: "you.better-call.dev"
    oauth:
        enabled: true
    sentry:
        enabled: true
        project: api
    networks:
        - mainnet
        - carthagenet
        - zeronet
        - babylonnet

indexer:
    sentry:
        enabled: true
        project: indexer
    networks:
        mainnet:
            boost: tzkt
        carthagenet:
            boost: tzkt
        zeronet:
            boost: tzkt
        babylonnet:
            boost: tzkt

metrics:
    sentry:
        enabled: true
        project: metrics
